name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Build, Run and test code
      run: |
        npm install
        npm run build
        npm run test
